apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  labels:
    app: hello-world
spec:
  type: NodePort
  selector:
    app: hello-world
  ports:
  - port: 32777
    targetPort: 32777
    nodePort: 30077
    protocol: TCP
  sessionAffinity: None
